version: '2'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: oscardog

#  vs-admin:
#    hostname: vs-admin
#    container_name: vs-admin
#    image: reidwelliver/vs-base:admin
#    build:
#      context: admin
#      dockerfile: docker/Dockerfile
#    depends_on:
#      - db
#    volumes:
#    - ./admin/:/project

  vs-auth:
    hostname: vs-accounts
    container_name: vs-accounts
    image: reidwelliver/vs-base:accounts
    build:
      context: accounts
      dockerfile: docker/Dockerfile
    links:
      - db:db
    depends_on:
      - db
    volumes:
    - ./accounts/:/project

  vs-room:
    hostname: vs-room
    container_name: vs-room
    image: reidwelliver/vs-base:room
    build:
      context: room
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
    - ./room/:/project
