version: '2'

services:
  db:
    image: vs-database
    container_name: vs-database
    image: mysql:latest
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  vs-accounts:
    hostname: vs-accounts
    container_name: vs-accounts
    image: reidwelliver/vs-base:accounts
    build:
      context: accounts
      dockerfile: docker/Dockerfile
    links:
      - db:db
    depends_on:
      - db
    volumes:
    - ./accounts/:/project

  vs-room:
    hostname: vs-room
    container_name: vs-room
    image: reidwelliver/vs-base:room
    build:
      context: room
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
    - ./room/:/project

  vs-web:
    hostname: vs-web
    container_name: vs-web
    image: reidwelliver/vs-base:web
    build:
      context: web
      dockerfile: docker/Dockerfile
    volumes:
    - "./web/:/project"
    ports:
    - "36080:80"
