#!/bin/bash
UTILDIR="$(pwd $(dirname "$0"))/utils"
source $UTILDIR/link "$@"

#absolute path to bind to docker
if hasopt --gitpath yes
then
	GITPATH=$(fetchopt --gitpath yes)
else
	GITPATH=$(pwd $(dirname "$0"))
fi


if hasopt --utildir yes
then
	UTILDIR=$(fetchopt --utildir yes)
fi

if hasopt --utildir yes
then
	BUILD_DEBUG="--build-arg BUILD_DEBUG=$(fetchopt --build-debug yes)"
else
	BUILD_DEBUG=""
fi

#TODO: if project subdir has a dockerfile, override call to this one


#Server Directory
requireopt -p yes
SERVDIR=$(fetchopt -p yes)


if [ ! -d $SERVDIR ]
then
	error "Your selected server is not a directory in the git project!"
	exit 1
fi


PORTCMD=$($UTILDIR/port-generator -f $SERVDIR/config/ports)
#todo: portcmd validation

#gathers argument and feeds to docker file
docker build -t reidwelliver/vs-base:$SERVDIR-build --build-arg SERV=$SERVDIR $BUILD_DEBUG ./

#TODO: map ports here
docker run --name vs-$SERVDIR-build $PORTCMD -v $GITPATH/$SERVDIR:/project -v $GITPATH/utils:/utils -i -t reidwelliver/vs-base:$SERVDIR-build /utils/run-wakeup
