#!/bin/bash

#TODO: allow gitpath to be entered
#TODO: improve parameter gathering (gatheropts)
#TODO: if project subdir has a dockerfile, override call to this one
#TODO: map ports here


#absolute path to bind to docker
GITPATH=`dirname "$0"`

#gathers argument and feeds to docker file
docker build -P --build-arg SERV=$1 --build-arg GITPATH=$GITPATH ./ 
