version: '2'

services:
  vs-web:
    hostname: vs-web
    container_name: vs-web
    image: reidwelliver/vs-base:web
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
    - ../:/project
    ports:
    - 40080:80
