#!/bin/bash
# Common useful BASH functions
# To include this write at the top of your script:
# source $UTILDIR/link "$@"
source $UTILDIR/link "$@"

# Process Line: reads in a line, skips if it's a comment
# Otherwise runs a callback
# @Param $1: line (String)
# @Param $2: callback (function) - should take line as first arg
function processline() {
	LINE=$1
	CALLBACK=$2

	if [[ -z `echo "$LINE" | grep "^#"` ]]
	then
		$CALLBACK "$LINE"
	fi
}


# Process File: reads in a file, runs Process Line on each line
# @Param $1: file (String)
# @Param $2: callback (function) - should take line as first arg
function processfile() {
	FILE=$1
	CALLBACK=$2

	while read LINE
	do
		processline "$LINE" $CALLBACK
	done < $FILE
}

# shortcut for checking if a string matches a grep
# @Param $1: String to check
# @Param $2: String to match against
function contains() {
	STRING=$1
	REGEX=$2

	MATCH=`echo "$STRING" | grep "$REGEX"` 
	
	if isempty $MATCH
	then
		return 1
	else
		return 0
	fi

}

# fetchopt
# This searches the parameters that we sourced into this script from the caller
# you give it a flag and whether it has an option, and it returns an exit code
# it also echoes the option (if selected) for capture
# @Param $1: string flag to search for
# @Param $2: (optional) non-null value signifying to echo the option
## Caveat: if you tell this function to find an option after the last parameter, it will exit code 1
## I think this is pretty sane behavior
function fetchopt() {
	FLAG=$1
	HASOPTION=$2
	ITER=0
	for ARG in $LIB_CALLER_PARAM
	do
		((ITER++))
		if contains "$ARG" "^$FLAG"
		then
			if ! isempty "$HASOPTION"
			then
				#I'm assuming if you bothered to set hasoption, it has an option
				OPTION="${LIB_CALLER_PARAM_ARRAY[$ITER]}"
				echo $OPTION
			else
				OPTION=1
			fi

			break	
		fi
	done



	if isempty $OPTION
	then
		return 1
	else
		return 0
	fi
}

#like fetchopt, but this will fail if it can't get an option
# @Param $1: string flag to search for
# @Param $2: (optional) non-null value signifying to echo the option
function requireopt() {
	OPT=$(fetchopt $1 $2)
	RETVAL=$?
	if [ $RETVAL -ne 0 ]
	then
		error "Invalid option given with $1"
		exit 1
	else
		return $RETVAL
	fi
}


#Shortcut to non-fatally check for option, suppresses output
# @Param $1: string flag to search for
# @Param $2: (optional) non-null value signifying to echo the option
function hasopt() {
	OPT=$(fetchopt $1 $2)
	return $?
}


function checksudo() {
	if [ "$(id -u)" -ne 0 ]
		then error "Please run $LIB_CALLER_NAME as root or with sudo"
		exit 1
	else
		return 0
	fi
}

return 0
