#!/bin/bash
# A place to mock functions for debugging

function apt-get() {
	ARGARR=($@)
	LASTARG=`expr $#-1`
	debug "This is a fake apt-get call"
	info "installing ${ARGARR[$LASTARG]}"
}

function service() {
	ARGARR=($@)
	LASTARG=`expr $#-2`
	debug "This is a fake service call"
	info "starting ${ARGARR[$LASTARG]}"
}

return 0