#!/bin/bash
DEBUG_METAPARAM="$@"
debug "DEBUG_METAPARAM: $DEBUG_METAPARAM"

function apt-get() {
	ARGARR=($@)
	LASTARG=`expr $#-1`
	debug "This is a fake apt-get call"
	info "installing ${ARGARR[$LASTARG]}"
}
