#!/bin/bash


# link - sources all bash directories, only once
# source this file to include all libs safely - use the following line
# source $UTILDIR/link "$@"


# shortcut for checking if a string isn't empty
# @Param $1: String to check for emptiness
function isempty() {
	STRING=$1

	if [ -z "$STRING" ]
	then
		return 0
	else
		return 1
	fi
}

function iscaller() {
	contains "$1" "$LIB_CALLER_NAME"
	return $?
}

if isempty "$LIB_LINK"
then
	LIB_LINK=1

	if isempty "$@"
	then
		LIB_CALLER_PARAM=""
		LIB_CALLER_NAME="library"
		LIB_CALLER_PARAM_ARRAY=("")
	else
		LIB_CALLER_PARAM="$@"
		LIB_CALLER_NAME=`basename $0`
		read -r -a LIB_CALLER_PARAM_ARRAY <<< "$LIB_CALLER_PARAM"
	fi

	isempty "$LIB_LINK_COMMON" && LIB_LINK_COMMON=1 && source $UTILDIR/common "$LIB_CALLER_PARAM"
	isempty "$LIB_LINK_LOGGER" && LIB_LINK_LOGGER=1 && source $UTILDIR/logger "$LIB_CALLER_PARAM"
	isempty "$LIB_LINK_DEBUG"  && ( hasopt "--util-debug" || ! isempty "$BUILD_DEBUG" ) && LIB_LINK_DEBUG=1 && source $UTILDIR/debug "$LIB_CALLER_PARAM"
fi

return 0