#!/bin/bash
source $UTILDIR/common "$@"

# script-runner - sanely runs all scripts in a folder


#TODO: collect args better, add arg to override default searching (currently hard set to 1 w/ SKIPDEF)
INDIR=$1
CONTDIR=`basename $INDIR`
SKIPDEF="1"
SCRIPTCOUNT=0
RUNCOUNT=0

#check if directory has executable scripts
ISEMPTY=`ls -al $INDIR | grep '^[^d][\-rw]*x'`


#check if input file exists, otherwise try to use base
if [ -d "$INDIR" -a ! empty "$ISEMPTY" ]
then
	info "Running all scripts from $INDIR"
elif ! empty "$SKIPDEF"
then
	info "$INDIR does not exist, is not a directory, or is empty."
	info "The flag to skip running defaults has been set, exiting."
	exit 0
else
	warn "$INDIR does not exist, is not a directory, or is empty."
	warn "Attempting to find default to satisfy $INDIR"

	DEFDIR="$UTILDIR/default/$CONTDIR"
	if [ -d "$DEFDIR" ]
	then
		warn "Found default directory $DEFDIR, proceeding."
		INDIR="$DEFDIR"
	else
		error "Could not find directory to run scripts from, exiting."
		exit 1
	fi
fi

for script in "$INDIR"/*
do
	let "SCRIPTCOUNT+=1"
	SCRIPTNAME=`basename $script`

	if [[ -x  "$script" ]]
	then
		let "RUNCOUNT+=1"
		info "Running $script, logging to $LOGDIR/$CONTDIR/$SCRIPTNAME"
		"$script" | "$UTILDIR"/logger "$LOGDIR/$CONTDIR/$SCRIPTNAME"
	else
		warn "Script $script is not marked executable. Skipping."
	fi
done

info "Ran $RUNCOUNT/$SCRIPTCOUNT scripts."