#!/bin/bash
source $UTILDIR/link "$@"

# script-runner - sanely runs all scripts in a folder

requireopt -d yes
INDIR=$(fetchopt -d yes)

CONTDIR=`basename $INDIR`
SKIPDEF=$(fetchopt -s)

NUMLN=0
NUMINS=0

#check if directory has executable scripts
ISEMPTY=$(ls -al $INDIR | grep '^[^d][\-rw]*x')


#check if input file exists, otherwise try to use base
if [ -d "$INDIR" ] || ! empty "$ISEMPTY"
then
	info "Running all scripts from $INDIR"
elif ! isempty "$SKIPDEF"
then
	info "$INDIR does not exist, is not a directory, or is empty."
	info "The flag to skip running defaults has been set, exiting."
	exit 0
else
	warn "$INDIR does not exist, is not a directory, or is empty."
	warn "Attempting to find default to satisfy $INDIR"

	DEFDIR="$UTILDIR/default/$CONTDIR"
	if [ -d "$DEFDIR" ]
	then
		warn "Found default directory $DEFDIR, proceeding."
		INDIR="$DEFDIR"
	else
		error "Could not find directory to run scripts from, exiting."
		exit 1
	fi
fi

for script in "$INDIR"/*
do
	((NUMLN++))
	SCRIPTNAME=`basename $script`

	if [[ -x  "$script" ]]
	then
		((NUMINS++))
		info "Running $script, logging to $(normalize $SCRIPTNAME)"
		"$script" | log "$SCRIPTNAME"
	else
		warn "Script $script is not marked executable. Skipping."
	fi
done

info "Ran $NUMINS/$NUMLN scripts."