version: '2'

services:
  vs-trackqueue:
    hostname: vs-trackqueue
    container_name: vs-trackqueue
    image: reidwelliver/vs-base:trackqueue
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
    - ../:/project
