version: '2'

services:
  vs-auth:
    hostname: vs-auth
    container_name: vs-auth
    image: reidwelliver/vs-base:auth
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
    - ../:/project
