version: '2'

services:
  vs-admin:
    hostname: vs-admin
    container_name: vs-admin
    image: reidwelliver/vs-base:admin
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
    - ../:/project
